name: NHAt
favicon: null
layout_spectrum: 0.29067
typography_spectrum: 0.46899462258443236
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.125
  lightness: 0.5279865218326449
  saturation: 0.5798387441318482
  rhythmicContrast: 0.5519868631381541
purpose: []
